name: backend CI/CD
# Give your workflow a meaningful name for easy identification.

on:
  push:
    branches:
      - main
# Trigger this workflow on each push to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest
    # Specify the runner environment for this job.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # This step checks out your code from the repository.

      - name: Clean and Install with Maven
        run: ./mvnw clean install
        # Clean and build your Maven project.

      - name: Set up Docker Buildx (optional but recommended)
        uses: docker/setup-buildx-action@v1
        # Set up Docker Buildx for building multi-platform images.

      - name: Set up Docker CLI
        run: docker login -u moislam -p ${{ secrets.BACKEND_ACCESS_TOKEN }}
        # Log in to your Docker Hub account using a secret for security.

      - name: Build and Push Docker Image
        run: |
          docker build -t moislam/backend-springboot-repository:latest .
          docker push moislam/backend-springboot-repository
        # Build your Docker image and push it to your Docker Hub repository.

      - name: Run Tests
        run: ./mvnw test
        # Execute tests for your application.

      - name: Log in to Docker Hub
        run: docker login -u moislam -p ${{ secrets.BACKEND_ACCESS_TOKEN }}
        # Log in to Docker Hub again; it might not be necessary if already logged in.

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yaml up -d
        # Start your application and its dependencies defined in 'docker-compose.yaml'.
